CREATE DATABASE WebApiBd
USE WebApiBd

CREATE TABLE Selecao (
	Id			INT PRIMARY KEY NOT NULL IDENTITY,
	Nome		VARCHAR(255) NOT NULL,
	Bandeira	IMAGE,
	Uniforma	IMAGE,
	Escalacao	VARCHAR(10)
)

CREATE TABLE Jogador (
	Id					INT PRIMARY KEY NOT NULL IDENTITY,
	Nome				VARCHAR(255) NOT NULL,
	Nascimento			DATETIME NOT NULL,
	Posicao				VARCHAR(255) NOT NULL,
	QTDEFaltas			INT NOT NULL DEFAULT(0),
	QTDECartoesAmarelo	INT NOT NULL DEFAULT(0),
	QTDECartoesVemelho	INT NOT NULL DEFAULT(0),
	Informacoes			TEXT NOT NULL,
	NumeroCamisa		INT NOT NULL,
	Foto				IMAGE,
	SelecaoID			INT FOREIGN KEY REFERENCES Selecao (Id)
)